package-lock.json, package.json, src/components/DynamicForm/DynamicForm.stories.tsx, src/components/DynamicForm/DynamicForm.tsx
- remove bootstrap
- use tailwind macro
=> fix: cleanup dynamicForm

src/components/DynamicFormContainer/DynamicForm/DynamicForm.tsx, src/components/DynamicFormContainer/DynamicFormLayout.tsx, src/components/DynamicFormContainer/TransferableRecordForm/TransferableRecordForm.tsx, src/components/PublishContainer/PublishPage/PublishPage.tsx, src/components/UI/Button/Button.tsx, src/styles/abstracts/variables.tsx, src/tailwind.js, src/test/fixtures/sample-config.json
- Upgraded UI to that of Design.
=> chore: update transferable UI

src/components/PublishContainer/PublishPage/PublishPage.tsx, src/components/PublishContainer/PublishedTag/PublishedTag.test.tsx, src/components/PublishContainer/PublishedTag/PublishedTag.tsx, src/components/PublishContainer/PublishedTag/index.tsx
- the I am done bug 
- refactor the download component
=> chore: fix iAmDone bug and refactor

netlify.toml
https://www.pivotaltracker.com/story/show/173913722
This prevents user from seeing a page not found error when navigating from a link or performing a hard refresh.
1. Go to https://deploy-preview-25--tradetrust-creator.netlify.app/form
2. Yay you are now at https://deploy-preview-25--tradetrust-creator.netlify.app/
=> chore: redirect all paths to /

src/components/DynamicFormContainer/BackModal/BackModal.tsx, src/components/DynamicFormContainer/DeleteModal/DeleteModal.tsx, src/components/DynamicFormContainer/DynamicFormHeader/DynamicFormHeader.tsx, src/components/FormSelectionContainer/FormSelection/FormSelection.tsx, src/components/PublishContainer/PublishedScreen/PublishedScreen.tsx, src/components/UI/Button/Button.tsx, src/test/fixtures/sample-config.json
In this PR: 
- updated the CSS for when user have multiple forms.
(previously it was cramping all up in 1 line)
=> chore: improve the CSS for more multiple forms

integration/integration-end-to-end.spec.ts, src/Router.tsx, src/components/UI/NetworkBar/NetworkBar.stories.tsx, src/components/UI/NetworkBar/NetworkBar.tsx, src/components/UI/NetworkBar/index.tsx, src/styles/abstracts/variables.tsx, src/tailwind.js
- add network indication based on config file
- https://www.pivotaltracker.com/story/show/174158204
=> feat: network bar

integration/integration-end-to-end.spec.ts, src/components/PublishContainer/PublishPage/PublishPage.test.tsx, src/components/PublishContainer/PublishedScreen/PublishedTag/PublishedTag.test.tsx, src/components/PublishContainer/PublishedScreen/PublishedTag/PublishedTag.tsx, src/tailwind.js
- Updated the name of the created file with the network.
(both on screen and when downloaded)
=> feat: updated file name with network appended at the end of it and update test cases

integration/integration-end-to-end.spec.ts, src/components/Home/ConfigFileDropZone/ConfigFileDropZone.tsx, src/components/Home/ConfigFileDropZone/ConfigFileDropZoneContainer.tsx, src/components/UI/SvgIcon/SvgIcon.stories.tsx, src/components/UI/SvgIcon/SvgIcon.tsx
- Added a button with link to docs.tradetrust.io
=> feat: added button to open new tab with docs

LICENSE, src/components/DynamicFormContainer/DynamicForm/CustomTemplates/CustomTextareaWidget.test.tsx, src/components/DynamicFormContainer/DynamicForm/CustomTemplates/CustomTextareaWidget.tsx, src/components/DynamicFormContainer/DynamicForm/CustomTemplates/index.tsx, src/components/DynamicFormContainer/DynamicForm/DynamicForm.tsx, src/test/fixtures/sample-config.json
- update the generic form template in the config file
- added custom text area widget so that we can have text area in the generic form template.
=> feat: update dynamic form to handle generic form template

src/test/fixtures/sample-config-fail-publish-document.json, src/test/fixtures/sample-config.json
- update generic template renderer url in sample-config file and in failed-sample-config
=> chore: update generic template renderer url

src/components/NavigationBar/NavigationBar.tsx, src/tailwind.js
- nav menu items updated
- https://www.pivotaltracker.com/story/show/174138261
=> feat: nav menu

integration/integration-end-to-end.spec.ts, package-lock.json, package.json, src/components/PublishContainer/PublishedScreen/PublishedScreen.test.tsx, src/components/PublishContainer/PublishedScreen/PublishedScreen.tsx, src/tailwind.js
- Added a button to download all successfully issued documents
=> feat: added download all documents as a zip folder

src/common/config/decrypt.tsx, src/components/Home/WalletDecryption/WalletDecryption.stories.tsx, src/components/Home/WalletDecryption/WalletDecryption.test.tsx, src/components/Home/WalletDecryption/WalletDecryption.tsx, src/components/Home/WalletDecryption/WalletDecryptionContainer.tsx, src/components/ProgressBar/ProgressBar.tsx
- add decrypt progress indicator
- refactor progress bar to reuse
=> feat: decrypt progress

integration/integration-fail-publish-document.spec.ts, src/common/config/decrypt.test.tsx, src/components/PublishContainer/PublishErrorScreen/PublishErrorScreen.tsx, src/components/PublishContainer/PublishedScreen/PublishedScreen.tsx, src/utils/fileName/fileName.test.tsx, src/utils/fileName/fileName.tsx
- Appended the date time to the back of the error log file name.
=> feat: updated error log with the date-time appended to the end of the file name

src/components/DynamicFormContainer/DynamicForm/AttachmentDropzone/FilesInfo/FilesInfo.tsx, src/components/Home/WalletDecryption/WalletDecryption.test.tsx, src/components/Home/WalletDecryption/WalletDecryption.tsx
- no such term as `metawallet`
=> chore: placeholder text change

src/components/DynamicFormContainer/DocumentSelector/DocumentSelector.stories.tsx, src/components/DynamicFormContainer/DocumentSelector/DocumentSelector.test.tsx, src/components/DynamicFormContainer/DocumentSelector/DocumentSelector.tsx, src/components/DynamicFormContainer/DynamicFormHeader/DynamicFormHeader.test.tsx, src/components/DynamicFormContainer/DynamicFormHeader/DynamicFormHeader.tsx, src/components/DynamicFormContainer/DynamicFormLayout.tsx
- updated the preview to close when switch documents
=> fix: doc preview to close when change doc

src/components/NavigationBar/NavigationBar.tsx, src/test/fixtures/sample-config.json
This PR is relevant to this story: https://www.pivotaltracker.com/story/show/175051665 but applying redirection to other navbar items
=> fix: nav bar redirection

.storybook/preview.js, src/components/PublishContainer/PublishErrorScreen/PublishErrorScreen.tsx, src/components/PublishContainer/PublishedScreen/PublishedScreen.stories.tsx, src/components/PublishContainer/PublishedScreen/PublishedScreen.tsx, src/components/PublishContainer/PublishedScreen/PublishedTag/PublishedTag.tsx, src/utils/fileName/fileName.test.tsx, src/utils/fileName/fileName.tsx
- append timestamp to zip file
- https://www.pivotaltracker.com/story/show/175161915
=> feat: zip timestamp

integration/integration-end-to-end.spec.ts, integration/integration-fail-publish-document.spec.ts, src/common/context/forms/index.tsx
This PR is for the story: https://www.pivotaltracker.com/story/show/175351262 which prefixes the the document type as the template selected.
=> feat: change document name according to template

package.json
- don't purge styles, need to rethink about styles sharing strategy again
=> fix: common styles

package-lock.json, package.json
- Bump up the version of trade trust ui component repo
=> feat: bump up tradetrust-ui-components version

package-lock.json, package.json, src/Router.tsx
- Bump up common ui to v1.7.2
- Refactor network bar component
=> feat: refactor network bar

src/components/DynamicFormContainer/DynamicFormLayout.test.tsx, src/components/DynamicFormContainer/TransferableRecordForm/TransferableRecordForm.test.tsx, src/components/DynamicFormContainer/TransferableRecordForm/TransferableRecordForm.tsx
- updated text from "Beneficiary" to "Owner"
=> feat: update text from bene to owner

package-lock.json, package.json
- updated ui library for the latest pagination component
=> feat: update pagination component from ui library

src/test/fixtures/sample-config-rinkeby.json, src/test/fixtures/sample-config-ropsten.json
https://www.pivotaltracker.com/story/show/176714866
Update configuration file to add in editable fields for scac and carrier name
=> chore: edit BL config

package-lock.json, package.json, src/common/config/decrypt.test.tsx, src/common/config/decrypt.tsx, src/config/config.ts
- version 2.0.1 was blocking the pipeline due to npm install failure
- bumped to version 2.1.0 which had some changes in exported members
- no guarantees gsn feature works, just unblocking the pipeline :D
=> chore: bumped opengsn to 2.1.0

integration/document-data-upload.spec.ts, src/common/context/forms/index.tsx, src/common/utils.tsx, src/components/DynamicFormContainer/DynamicForm/DynamicForm.tsx
https://www.pivotaltracker.com/story/show/176991621
- invoice currently is the template that is making use of csv data file upload
- fix bug that only happens only on 2nd document onwards, after u add invoice template through add document (having a document prior to this)
=> fix: fix crash csv upload

integration/buttons.spec.ts, src/components/Home/ConfigFileDropZone/ConfigFileDropZoneContainer.tsx
=> fix: page url updated

src/components/PublishContainer/PublishedScreen/PublishedScreen.stories.tsx, src/components/PublishContainer/PublishedScreen/PublishedScreen.test.tsx, src/components/PublishContainer/PublishedScreen/PublishedScreen.tsx
- add fail docs download
- https://deploy-preview-110--tradetrust-creator-storybook.netlify.app/?path=/story/publishpage-publishedscreen--failed
=> feat: fail download button

package-lock.json, package.json, src/tailwind.css
- Fixed the issue with the spinner
=> fix: spinner from UI component library

src/test/fixtures/sample-config-rinkeby.json, src/test/fixtures/sample-config-ropsten.json
Updated token registry addresses in sample config files with @govtechsg/token-registry@2.5.2
=> fix: update token registries in config file

src/components/DynamicFormContainer/DataFileButton/DataFileButton.tsx, src/components/UI/ToolTip/ToolTip.stories.tsx, src/components/UI/ToolTip/ToolTip.test.tsx, src/components/UI/ToolTip/ToolTip.tsx, src/components/UI/ToolTip/index.tsx, src/tailwind.js
=> feat: add a tooltip component accordingly to the UI

src/common/config/decrypt.test.tsx, src/test/fixtures/sample-config-ropsten-aws.json
Removing AWS KMS decrypt test that uses aws account.
=> fix: remove aws kms decrypt test

integration/buttons.spec.ts, integration/document-attachments.spec.ts, integration/document-data-upload-error.spec.ts, integration/document-data-upload.spec.ts, integration/document-extension.spec.ts, integration/document-preview.spec.ts, integration/document-rename.spec.ts, integration/error-attachment-limit.spec.ts, integration/error-document-issue.spec.ts, integration/error-password-login.spec.ts, integration/happy-flow.spec.ts, integration/revoke-document.spec.ts, integration/ui-schema.spec.ts, src/components/NavigationBar/NavigationBar.test.tsx, src/components/ProgressBar/ProgressBar.test.tsx, src/components/ProgressBar/ProgressBar.tsx, src/tailwind.js
- change progress bar
- updated tests affected by above change
=> feat: changed progress bar

integration/document-extension.spec.ts, integration/happy-flow.spec.ts, integration/ui-schema.spec.ts
- lets omit this problematic assertion and monitor for awhile
- related = https://github.com/TradeTrust/document-creator-website/pull/137
=> fix: e2e flakes 2

integration/revoke-document.spec.ts, src/components/ProcessDocumentScreen/ProcessDocumentScreen.test.tsx, src/components/ProcessDocumentScreen/ProcessDocumentScreen.tsx, src/components/ProcessDocumentScreen/ProcessDocumentTitle/ProcessDocumentTitle.test.tsx, src/components/ProcessDocumentScreen/ProcessDocumentTitle/ProcessDocumentTitle.tsx, src/components/RevokeContainer/RevokeDocumentDropZone/RevokeDocumentDropZone.tsx, src/components/RevokeContainer/RevokeDocumentTileArea/RevokeDocumentTileArea.tsx
- Updated the text as discussed in the story review meeting.
- from 'file' to 'document' 
- remove '(s)' for revoke flow
=> fix: text for revoke flow

integration/buttons.spec.ts, integration/document-attachments.spec.ts, integration/document-data-upload-error.spec.ts, integration/document-data-upload.spec.ts, integration/document-extension.spec.ts, integration/document-preview.spec.ts, integration/document-rename.spec.ts, integration/error-attachment-limit.spec.ts, integration/error-configs.spec.ts, integration/error-document-issue.spec.ts, integration/error-password-login.spec.ts, integration/happy-flow.spec.ts, integration/revoke-document.spec.ts, integration/ui-schema.spec.ts, src/components/Home/WalletDecryption/WalletDecryption.test.tsx, src/components/Home/WalletDecryption/WalletDecryption.tsx
- finalised login page ui (change text, alignment and tests)
=> feat: finalised login page ui

integration/settings.spec.ts, public/index.html, src/components/AddressBookContainer/AddressBookContainer.tsx, src/components/AddressResolverContainer/AddressResolverContainer.tsx, src/components/NavigationBar/NavigationBar.tsx, src/components/SettingsContainer/SettingsContainer.tsx, src/tailwind.css
- should have its own settings page
- update font families, no more montserrat, source sans pro
- base style to follow tt-web
=> fix: settings page

src/components/UI/ContentFrame/ContentFrame.tsx
- fixed issue where the content becomes too small at certain view widths
=> fix: changed content frame to resize content better

integration/buttons.spec.ts, integration/document-attachments.spec.ts, integration/document-data-upload-error.spec.ts, integration/document-data-upload.spec.ts, integration/document-extension.spec.ts, integration/document-preview.spec.ts, integration/document-rename.spec.ts, integration/error-attachment-limit.spec.ts, integration/error-document-issue.spec.ts, integration/error-password-login.spec.ts, integration/happy-flow.spec.ts, integration/revoke-document.spec.ts, integration/ui-schema.spec.ts, src/components/FormSelectionContainer/FormSelection/FormSelection.tsx, src/components/UI/IssueOrRevokeSelector/IssueOrRevokeSelector.tsx
- updated title -> h3
- changed some text
=> feat: updated choose document ui

integration/buttons.spec.ts, integration/document-attachments.spec.ts, integration/document-data-upload-error.spec.ts, integration/document-data-upload.spec.ts, integration/document-extension.spec.ts, integration/document-preview.spec.ts, integration/document-rename.spec.ts, integration/error-attachment-limit.spec.ts, integration/error-configs.spec.ts, integration/error-document-issue.spec.ts, integration/error-password-login.spec.ts, integration/happy-flow.spec.ts, integration/revoke-document.spec.ts, integration/ui-schema.spec.ts, src/components/DynamicFormContainer/DynamicFormHeader/DynamicFormHeader.tsx, src/components/FormSelectionContainer/FormSelection/FormSelection.tsx, src/components/Home/ConfigFileDropZone/ConfigFileDropZone.tsx, src/components/Home/WalletDecryption/WalletDecryption.tsx, src/components/ProcessDocumentScreen/ProcessDocumentTitle/ProcessDocumentTitle.tsx, src/components/RevokeContainer/RevokeDocumentDropZone/RevokeDocumentDropZone.tsx
- replace most Title components with h* tags
- replaced selectors in test from h* tags to data-testid
=> chore: replaced h-selectors in test files with testids

integration/buttons.spec.ts, integration/document-preview.spec.ts, src/components/DynamicFormContainer/DataFileButton/DataFileButton.tsx, src/components/DynamicFormContainer/DynamicForm/AttachmentDropzone/AttachmentDropzone.tsx, src/components/DynamicFormContainer/DynamicForm/DynamicForm.tsx, src/components/DynamicFormContainer/DynamicFormHeader/DynamicFormHeader.test.tsx, src/components/DynamicFormContainer/DynamicFormHeader/DynamicFormHeader.tsx, src/components/DynamicFormContainer/DynamicFormLayout.test.tsx, src/components/DynamicFormContainer/DynamicFormLayout.tsx, src/components/FormSelectionContainer/FormSelection/FormSelection.tsx, src/components/RevokeContainer/RevokeDocumentDropZone/RevokeDocumentDropZone.tsx, src/components/RevokeContainer/RevokeDocumentTileArea/RevokeDocumentTileArea.tsx, src/components/UI/IssueOrRevokeSelector/IssueOrRevokeSelector.stories.tsx, src/components/UI/IssueOrRevokeSelector/IssueOrRevokeSelector.tsx, src/components/UI/ToggleSwitch/ToggleSwitch.tsx, src/tailwind.js
- updated tests related to changes on the fill form page
- reworked switch component
- change text and colors
=> feat: update fill form ui

package-lock.json, package.json, src/Router.tsx, src/components/NavigationBar/NavigationBar.tsx, src/components/ProcessDocumentScreen/ProcessDocumentScreen.test.tsx, src/components/ProcessDocumentScreen/ProcessDocumentScreen.tsx, src/components/ProcessDocumentScreen/ProcessDocumentTitle/ProcessDocumentTitle.tsx
- upgraded ui components for new navbar
- updated error styles
=> chore: upgraded tt-ui-components

integration/buttons.spec.ts, src/components/DynamicFormContainer/BackModal/BackModal.test.tsx, src/components/DynamicFormContainer/BackModal/BackModal.tsx, src/components/ModalDialog/ModalDialog.test.tsx, src/components/ModalDialog/ModalDialog.tsx, src/components/RevokeContainer/RevokeConfirmationModal/RevokeConfirmationModal.tsx, src/components/RevokeContainer/RevokeDocumentTileArea/RevokeDocumentTileArea.tsx
- updated modal ui
- removed tailwind for modal
=> feat: update modal ui

src/components/DynamicFormContainer/DataFileButton/DataFileButton.tsx, src/components/DynamicFormContainer/DynamicForm/AttachmentDropzone/AttachmentDropzone.tsx, src/components/DynamicFormContainer/DynamicForm/DynamicForm.tsx, src/components/DynamicFormContainer/DynamicFormHeader/DynamicFormHeader.tsx, src/components/FormSelectionContainer/FormSelection/FormSelection.tsx, src/components/ProcessDocumentScreen/ProcessDocumentTitle/ProcessDocumentTitle.tsx
- fixed mobile ui display on various pages where component not properly aligned
- updated form ui
=> fix: mobile ui display now looks correct

src/tailwind.css
- react-jsonschema-form dynamic markup css classes not detected, hence gotten purged at build time
- purge ignore lines on styles for those 3rd library markup
=> fix: purge ignore

package-lock.json, package.json, src/components/DynamicFormContainer/DynamicForm/CustomTemplates/CustomDropdownWidget.test.tsx, src/components/DynamicFormContainer/DynamicForm/CustomTemplates/CustomDropdownWidget.tsx, src/components/DynamicFormContainer/DynamicForm/CustomTemplates/index.tsx, src/components/DynamicFormContainer/DynamicForm/DynamicForm.tsx, src/tailwind.css, src/test/fixtures/sample-config-geekout.json
- https://www.pivotaltracker.com/story/show/178984520
- custom widget, reuse dropdown
previously:
current pr:
https://user-images.githubusercontent.com/4774314/132654766-7a42ab5d-2cd1-472f-8f44-377e016f12ed.mp4
=> feat: custom dropdown widget

integration/error-document-issue.spec.ts, package-lock.json, src/components/DynamicFormContainer/DynamicFormHeader/DynamicFormHeader.tsx, src/components/DynamicFormContainer/FormErrorBanner/FormErrorBanner.tsx, src/components/FormSelectionContainer/FormSelection/FormSelection.tsx, src/components/Home/WalletDecryption/WalletDecryption.tsx, src/components/ModalDialog/ModalDialog.tsx, src/components/ProcessDocumentScreen/ProcessDocumentContent/ProcessDocumentContent.stories.tsx, src/components/ProcessDocumentScreen/ProcessDocumentContent/ProcessDocumentContent.tsx, src/components/ProcessDocumentScreen/ProcessDocumentContent/index.tsx, src/components/ProcessDocumentScreen/ProcessDocumentScreen.test.tsx, src/components/ProcessDocumentScreen/ProcessDocumentScreen.tsx, src/components/ProcessDocumentScreen/ProcessDocumentTitle/ProcessDocumentTitle.stories.tsx, src/components/ProcessDocumentScreen/ProcessDocumentTitle/ProcessDocumentTitle.test.tsx, src/components/ProcessDocumentScreen/ProcessDocumentTitle/ProcessDocumentTitle.tsx, src/components/ProcessDocumentScreen/ProcessedDocumentTag/ProcessedDocumentTag.tsx, src/components/ProgressBar/ProgressBar.stories.tsx, src/components/ProgressBar/ProgressBar.test.tsx, src/components/ProgressBar/ProgressBar.tsx, src/components/RevokeContainer/RevokeDocumentDropZone/RevokeDocumentDropZone.tsx, src/components/RevokeContainer/RevokeDocumentTileArea/RevokeDocumentTileArea.tsx, src/components/UI/ErrorCard/ErrorCard.tsx, src/components/UI/ErrorCard/index.tsx
- updated processing page ui
[Figma](https://www.figma.com/file/8GOvq1FnnTvxuKQydN9tBJ/TradeTrust-redesign-R2?node-id=4575%3A26927)
**All Documents Issued Success**
**All Documents Issued Failure**
**Some Success Some Fail**
=> feat: updated processing page ui

src/components/DynamicFormContainer/BackModal/BackModal.tsx, src/components/DynamicFormContainer/DeleteModal/DeleteModal.tsx, src/components/DynamicFormContainer/DynamicFormHeader/DynamicFormHeader.tsx, src/components/Home/ConfigFileDropZone/ConfigFileDropZone.tsx, src/components/Home/WalletDecryption/WalletDecryption.tsx, src/components/ModalDialog/ModalDialog.tsx, src/components/RevokeContainer/RevokeConfirmationModal/RevokeConfirmationModal.tsx, src/components/UI/IssueOrRevokeSelector/IssueOrRevokeSelector.tsx, src/components/UI/ToggleSwitch/ToggleSwitch.tsx
- made ui fixes according to figma
=> fix: made ui fixes

src/components/DynamicFormContainer/DynamicFormLayout.tsx, src/components/OnCloseGuard/OnCloseGuard.tsx, src/components/OnCloseGuard/index.tsx
- add confirmation modal when user attempts to close the browser when there is an active form
=> feat: added browser close guard

src/components/ConfirmModal/ConfirmModal.tsx, src/components/DynamicFormContainer/AddFormModal/AddFormModal.tsx, src/components/DynamicFormContainer/DataFileButton/DataFileButton.tsx, src/components/DynamicFormContainer/DynamicForm/AttachmentDropzone/AttachmentDropzone.tsx, src/components/DynamicFormContainer/DynamicFormHeader/DynamicFormHeader.tsx, src/components/Home/ConfigFileDropZone/ConfigFileDropZone.tsx, src/components/Home/ConfigFileDropZone/ConfigFileDropZoneContainer.test.tsx, src/components/Home/WalletDecryption/WalletDecryption.tsx, src/components/NavigationBar/NavigationBar.tsx, src/components/ProcessDocumentScreen/ProcessDocumentContent/ProcessDocumentContent.tsx, src/components/ProcessDocumentScreen/ProcessedDocumentTag/ProcessedDocumentTag.tsx, src/components/RevokeContainer/RevokeDocumentDropZone/RevokeDocumentDropZone.tsx, src/components/RevokeContainer/RevokeDocumentTileArea/RevokeDocumentTileArea.tsx, src/components/UI/ToggleSwitch/ToggleSwitch.tsx, src/test/fixtures/sample-config-local.json, src/test/fixtures/sample-config-rinkeby.json, src/test/fixtures/sample-config-ropsten-aws.json, src/test/fixtures/sample-config-ropsten.json
=> fix: changed config file labels

integration/document-data-upload.spec.ts, integration/document-preview.spec.ts, integration/document-rename.spec.ts, integration/error-attachment-limit.spec.ts, integration/happy-flow.spec.ts, src/common/hook/useQueue/utils/sample-config.json, src/test/fixtures/sample-config-local-v3.json, src/test/fixtures/sample-config-local.json, src/test/fixtures/sample-config-rinkeby.json, src/test/fixtures/sample-config-ropsten-aws.json, src/test/fixtures/sample-config-ropsten-v3.json, src/test/fixtures/sample-config-ropsten.json
Update template name as the template has specific use case. Other user story are preparing other COO template that are more towards generic COO template
COO -> COO (ChAFTA)
Certificate of origin -> Certificate of origin (ChAFTA)
=> fix: update template name and test

package-lock.json, package.json, src/pages/pageNotFound.tsx
This PR is to update the existing page 404 with the updated design
* update common ui deps
* Changed to use the new component <Page404>
story: https://www.pivotaltracker.com/n/projects/2424361/stories/179588695
Channels: latest
ETA: Any target release date
=> feat: updated page 404 with the new component

src/common/API/storageAPI.tsx, src/common/hook/useQueue/utils/publish.tsx
Fixing documentStorage for version 3 document
- Placing link.self.link in credentialSubject for version 3 document
What are the related issues or stories?
=> fix: v3 documentStorage

package-lock.json, src/common/hook/useQueue/useQueue.tsx, src/components/DynamicFormContainer/DataFileButton/DataFileButton.tsx, src/components/Home/ConfigFileDropZone/ConfigFileDropZone.tsx, src/components/Home/ConfigFileDropZone/ConfigFileDropZoneContainer.tsx, src/components/Home/WalletDecryption/WalletDecryptionContainer.tsx, src/components/ProcessDocumentScreen/ProcessDocumentContent/ProcessDocumentContent.tsx, src/components/ProcessDocumentScreen/ProcessedDocumentTag/ProcessedDocumentTag.tsx, src/components/RevokeContainer/RevokeDocumentDropZone/RevokeDocumentDropZone.tsx
Update revoke UI to look like the redesign in figma 
- Update some UI to look like the redesign in figma
- update some lint errors
https://www.pivotaltracker.com/n/projects/2424361/stories/179279240
https://www.figma.com/file/8GOvq1FnnTvxuKQydN9tBJ/TradeTrust---redesign-R2?node-id=1492%3A12518
=> fix: update revoke UI and lint error

src/common/hook/useQueue/utils/publish.tsx, src/test/fixtures/config/_generated-config-files/sample-config-ropsten.json, src/test/fixtures/config/configuration-file.ts
Enable OpenAttestation version 2 and 3 document to be issued In 1 process flow
- Added a configuration file that contains both version 2 and version 3 document 
- Modify publish job process flow for verifiable document batch and wrapping
-
=> feat: issue v2 and v3 document

src/test/fixtures/config/_generated-config-files/sample-config-ropsten.json, src/test/fixtures/config/_generated-config-files/test/config-empty-wallet.json, src/test/fixtures/config/_generated-config-files/test/config-invalid-issuer.json, src/test/fixtures/config/_generated-config-files/test/sample-config-local.json, src/test/fixtures/config/_generated-config-files/v2/sample-config-did.json, src/test/fixtures/config/_generated-config-files/v2/sample-config-rinkeby.json, src/test/fixtures/config/_generated-config-files/v2/sample-config-ropsten-aws.json, src/test/fixtures/config/_generated-config-files/v2/sample-config-ropsten.json, src/test/fixtures/config/forms/v2/coo-simple.json
Adding Simple COO template into the configuration files
- Included Simple COO template into forms folder
- Added the template into forms V2
- Update the configuration files using the generator
https://www.pivotaltracker.com/story/show/179932523
=> feat: simple coo

src/common/hook/useQueue/utils/publish.tsx
=> fix: remove console log

package-lock.json, package.json, postcss.config.js, public/index.html, src/tailwind.css, src/tailwind.js
- rebranding font replace roboto with gilroy
=> feat: font gilroy

package-lock.json, package.json, src/components/NavigationBar/NavigationBar.stories.tsx, src/components/NavigationBar/NavigationBar.tsx
- update logo size for nav bar
- update logo size for footer
=> fix: update to latest navbar

package-lock.json, package.json
=> fix: update nav bar

src/common/hook/useQueue/utils/publish.tsx, src/common/utils.tsx
- credentialSubject for v3 docs is empty, validate keep failing
- urgent fix
=> fix: v3 hotfix

package-lock.json, package.json, src/common/config/validate.tsx, src/constants/chainInfo.tsx
Update the network in config files for document creation
- update to allow more network for document creation
https://www.pivotaltracker.com/n/projects/2424361/stories/181365136
=> feat: update to allow more network

integration/custom-array-field-ordering.spec.ts, integration/helper.ts, src/common/config/decrypt.test.tsx, src/common/config/decrypt.tsx, src/common/hook/useQueue/useQueue.test.tsx, src/common/utils.tsx, src/constants/chainInfo.tsx, src/services/publishing/publishing.ts, src/test/fixtures/config/v2/sample-config-goerli.json
Enable Goerli title escerow and update rinkeby rpc url
- enable goerli title escrow
- update rinkeby rpc url
- update the way we using provider
=> feat: update rpc url for rinkeby and support goerli token registry

src/common/utils.tsx, src/components/DynamicFormContainer/DynamicForm/CustomTemplates/CustomFileWidget.test.tsx, src/components/DynamicFormContainer/DynamicForm/CustomTemplates/CustomFileWidget.tsx
- attachment upload and file widget not working
- omit `attachment` validate, it is not part of form data schema
- call filewidget onChange 
- https://www.pivotaltracker.com/story/show/183625781
- https://www.pivotaltracker.com/story/show/183625650
=> fix: attachment and file widget

src/constants/chainInfo.tsx, src/services/publishing/publishing.ts
Update Polygon mumbai RPC URL.
- update polygon mumbai rpc url
=> fix: update polygon rpc url

src/common/utils.tsx
- v3 issue encountering validation error of network
- made a mistake for v3 `network` omit previously [here](https://github.com/TradeTrust/document-creator-website/pull/277/files?diff=unified&w=0#diff-75515acae3c848293093531617e760d55102a63197c4bcda703532b95b0e89fbR139)
- omit `network` at the correct function instead
=> fix: v3 network

src/constants/chainInfo.tsx
=> fix: test rpc fix

src/common/config/validate.tsx, src/constants/chainInfo.tsx, src/types/index.d.ts
This PR adds support for [Stability Testnet](https://github.com/stabilityprotocol/) network.
- Added stability network
NA
For further information, please reach the following email: [kerk@stabilityprotocol.com](mailto:kerk@stabilityprotocol.com)
=> [WIP] feat(stability): added support for stability network

src/components/Home/ConfigFileDropZone/ConfigFileDropZone.tsx, src/components/Home/ConfigFileDropZone/ConfigFileDropZoneContainer.test.tsx
=> fix: update broken link

package-lock.json, package.json
=> fix: axios

src/common/hook/useQueue/utils/publish.tsx, src/constants/chainInfo.tsx
fix list of mainnet so QR generation will be correct
=> fix: update list of mainnet for QR generation

src/common/hook/useQueue/utils/sample-formatted.json, src/common/utils.test.tsx, src/common/utils.tsx
fix: update oa to tradetrust action link
=> fix: update action link

src/App.tsx
=> fix: remove banner

netlify.toml
Reverts TradeTrust/document-creator-website#340
=> Revert "fix: update headers"

src/components/NavigationBar/NavigationBar.tsx, src/constants/Urls.tsx
What is the background of this pull request?
- What are the changes made in this pull request?
- Change this and that, etc...
What are the related issues or stories?
=> fix: nagvigate to tradetrust info site on logo click

package-lock.json, src/constants/chainInfo.tsx
What is the background of this pull request?
- Update chain value in chain info
=> fix: astron chain info

config-overrides.js, package-lock.json, package.json, src/common/utils.tsx, src/components/DynamicFormContainer/DataFileButton/DataFileButton.tsx, src/services/publishing/publishing.test.ts, src/services/publishing/publishing.ts
What is the background of this pull request?
- Minting for V5 Token Registry is not working.
- What are the changes made in this pull request?
- Updated function to support v5 token registry minting, with empty remarks.
=> feat: allow v5 minting

src/constants/chainInfo.tsx
What is the background of this pull request?
- Update xdc rpc
=> fix: xdc rpc

src/components/Home/ConfigFileDropZone/ConfigFileDropZone.tsx, src/components/Home/ConfigFileDropZone/ConfigFileDropZoneContainer.test.tsx
Update the link to button "Learn how to create one"
[Jira Ticket](https://afa-cdi.atlassian.net/browse/TT-612?atlOrigin=eyJpIjoiNTgxNTczOGIyMWFkNDVmNTgzYzRiZTYzZjM5NDRjNGUiLCJwIjoiaiJ9)
=> fix: update v4 learn more link
